### ISSUE TITLE
How to reexecute the query using atomsWithQuery?

### ISSUE THREAD

**Issue by RIP21** [jotaijs/jotai-urql#10]
In the original urql docs in order to refetch data you do this
```ts
const Todos = ({ from, limit }) => {
  const [result, reexecuteQuery] = useQuery({
    query: TodosListQuery,
    variables: { from, limit },
  });

  const refresh = () => {
    // Refetch the query and skip the cache
    reexecuteQuery({ requestPolicy: 'network-only' });
  };
};
```

In the case of Jotai `atomsWithQuery` helper. it returns a dispatch as a second parameter.

So 
```ts
const [burgersAtom] = atomsWithQuery(Index_BurgersDocument, () => ({}))
// ...

const [data, dispatch] = useAtom(burgersAtom)

const refresh = () => {
    // This should trigger reexecute. But it does trigger the execute ONLY if an entire strategy of the default client is `network-only` or `cache-and-network` (also triggers 80-90 requests. for some reason in that case)
   dispatch({ type: "refetch"}) 
};
```

The expected behavior would be something like 
```ts
dispatch({ type: "reexecute", options: { requestPolicy: 'network-only' })
```
 but I don't see in the source code or typings how this is possible.
 
 Also, unsure if it's possible to get paused query, e.g. behavior like here
 https://formidable.com/open-source/urql/docs/basics/react-preact/#pausing-usequery
 
 Probably it's possible to somehow hack around it using some custom-written helpers that will be using `client` atom. But unsure if this shouldn't be a part of the library itself. How is it handled in `react-query` jotai helpers? I assume it's much more popular, so it should support a majority of its (react-querie's) API out of the box that may apply to URQL. If not 1:1, but closely.

**Comment by dai-shi** [comment]
I hope someone can help on this.

jotai-urql is based on urql-core. Do you know if such options are exposed there?

**Comment by RIP21** [comment]
> I hope someone can help on this.
> 
> jotai-urql is based on urql-core. Do you know if such options are exposed there?

Yes, I mentioned them in the issue with the example.

**Comment by dai-shi** [comment]
> Yes, I mentioned them in the issue with the example.

Do you mean the example with `useQuery`? (I wasn't confident if it's the same with uqrl-core.)
Anyway, I think you are right, and if those options are exposed. It should be possible. I hope you or someone can dig into it.

**Comment by RIP21** [comment]
@dai-shi I would add some PRs soon, hopefully, today.
