### ISSUE TITLE
doesn't seem to recalc the atom on cache updates

### ISSUE THREAD

**Issue by scamden** [jotaijs/jotai-urql#18]
Repro:
1. Make an atomWithQuery 
2. useAtom on your query atom
3. Have some other UI update the graphcache entry that the query returns

Expected:
that atom updates with the new value

Actual:
No update

cc: @juliette-pouchol

**Comment by RIP21** [comment]
We would need an actual code snippet, or, better a reproduction.
Info given isn't enough to triage it.

**Comment by scamden** [comment]
Well I guess the first question would be: is this expected to work? I can work on a repro but I thought I would see if this was obvious to you first. Cache updates are pretty basic urql

**Comment by RIP21** [comment]
It should work, it subscribes to the changes of the items that are in the query.

**Comment by scamden** [comment]
i'll work on nailing down a repro soon then

**Comment by scamden** [comment]
so i finally painstakingly put together our use case in codesandbox: https://codesandbox.io/p/sandbox/urql-client-side-suspense-demo-81obe?file=%2Fsrc%2Findex.js%3A22%2C44

And it didn't repro 🤦 

I dug harder in our code and it turns out we weren't using the same client, because we were using `useHydrateAtoms([clientAtom, client])` but our client gets recreated and memoized on a couple props. Changing to both hydrate and set the atom in a useEffect fixed this. Sorry to take up attention, but leaving our root cause and fix here in case anyone else runs into this. 

Thanks again for this great library, which _does not_ have this bug :D

**Comment by RIP21** [comment]
@scamden Yay! Pretty happy my work (and a lot of tests) did pay off :D

Happy hacking! Also, be aware that Next + Suspense may cause some weird freezes and hangouts of the entire page on route change that irrecoverable. But only in production build and with old router.
At least, once, I had this problem and I didn't manage to solve it for weeks. Only solution was to revert the changes and keep using 'loading' and stuff like that.

But I hope you'll never run into that problem :)

**Comment by scamden** [comment]
>(and a lot of tests)

love this.

> Also, be aware that Next + Suspense may cause some weird freezes and hangouts of the entire page on route change that irrecoverable.

oh dang! good to know! I have seen some "stuck in suspense" things, but so far the fix was to put a suspense boundary between the nearest jotai-scope provider and the suspending atom. This frightens me that this happened to you only in production though and I love the ergonomics of suspense so I don't want to stop lol. 

Any more detail on when this happened to you? What version of next? was it a route change during an urql query?

**Comment by RIP21** [comment]
@scamden to be completely honest I don't remember details, but it was super weird and it didn't work either it was suspended by URQL, or was suspended by just an async atom. And even a different sequence of visiting the routes was affecting it. If you do it in the 1 - 2 - 3 sequence it freezes at 3. But if you do 1 - 3 - 2 it does not :) So it was pretty weird. It was on Next 12 AFAIR.

So yeah, weird stuff :) Maybe with the app router it's no longer a thing, but for a page router it was there and it was a major PAIN as I had to revert 3 weeks of work :P
